# Generated by Django 3.2.16 on 2025-12-21 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_congratulation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Congratulation',
            new_name='Comment',
        ),
    ]
